apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: backups.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: example.com
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: backups
    # singular name to be used as an alias on the CLI and for display
    singular: backup
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Backup
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - bk
  scope: Namespaced
  versions:
  - name: v1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              cronExpression:
                type: string
                description: "The schedule in Cron format"
              podName:
                type: string
                description: "Target Pod to backup"
              path:
                type: string
                description: "Directory path inside the pod to backup"
            required: ["cronExpression", "podName", "path"]
    
    # Custom Columns for kubectl get
    additionalPrinterColumns:
    - name: Schedule
      type: string
      jsonPath: .spec.cronExpression
      description: Frequency of the backup
    - name: Target_Pod
      type: string
      jsonPath: .spec.podName
    - name: Path
      type: string
      jsonPath: .spec.path
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp