apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 56.6.2 # Stable version
    helm:
      values: |
        grafana:
          adminPassword: "admin" # dummy password for demo purposes
          ingress:
            enabled: false # port-forwarding for now
        prometheus:
          prometheusSpec:
            resources:
              requests:
                memory: "400Mi"
                cpu: "200m"
              limits:
                memory: "800Mi"
                cpu: "500m"
            storageSpec:
              # Persistent Storage
              # On Kind, this uses the local-path provisioner
              volumeClaimTemplate:
                spec:
                  storageClassName: "standard"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true