apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-flask
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mustafa-wr/Kubernetes-Platform-Engineering
    targetRevision: HEAD
    path: Falcon-Platform/internal-charts/standard-service
    helm:
      parameters:
        - name: image.repository
          value: 5790bb4d92ab3940083e586c2f2907fb4ec4a86b
        - name: image.tag
          value: f0e057dead6391ed0e82f14694aebec9c396ffd8
        - name: replicaCount
          value: 5790bb4d92ab3940083e586c2f2907fb4ec4a86b
        - name: service.port
          value: 5790bb4d92ab3940083e586c2f2907fb4ec4a86b
        - name: service.targetPort
          value: 5790bb4d92ab3940083e586c2f2907fb4ec4a86b
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
