apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-flask
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mustafa-wr/Kubernetes-Platform-Engineering
    targetRevision: HEAD
    path: Falcon-Platform/internal-charts/standard-service
    helm:
      parameters:
        - name: image.repository
          value: 039cf5e40aee6de1ef746ebbd10e41aa3c1026db
        - name: image.tag
          value: 039cf5e40aee6de1ef746ebbd10e41aa3c1026db
        - name: replicaCount
          value: 039cf5e40aee6de1ef746ebbd10e41aa3c1026db
        - name: service.port
          value: 039cf5e40aee6de1ef746ebbd10e41aa3c1026db
        - name: service.targetPort
          value: 039cf5e40aee6de1ef746ebbd10e41aa3c1026db
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true