# 1. High Priority for System Critical Pods
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: falcon-critical
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    role: observability