apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-root-user
  annotations:
    policies.kyverno.io/title: Disallow Root User
    policies.kyverno.io/description: >-
      Running as root is dangerous. Containers must specify runAsNonRoot: true.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-run-as-non-root
      match:
        any:
        - resources:
            kinds:
            - Pod
      exclude:
          any:
          - resources:
              namespaces:
              - local-path-storage  # Allow the storage helper to run
              - kube-system        # Allow system components to run
      validate:
        message: "Running as root is forbidden. Set securityContext.runAsNonRoot to true."
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true