apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falcon-core
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mustafa-wr/Kubernetes-Platform-Engineering.git
    # Pointing to the core folder
    path: Falcon-Platform/gitops/core
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true