apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falcon-root
  namespace: argoproj
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/falcon-platform.git
    targetRevision: main
    path: gitops/apps  # ArgoCD will recursively look inside this folder
  destination:
    server: https://kubernetes.default.svc
    namespace: argoproj
  syncPolicy:
    automated:
      prune: true      
      selfHeal: true    