apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falcon-root
  namespace: argocd   # <--- Make sure this is 'argocd', not 'argoproj' (common typo)
spec:
  project: default
  source:
    repoURL: https://github.com/mustafa-wr/Kubernetes-Platform-Engineering.git
    
    path: Falcon-Platform/gitops/apps  
    
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
